name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.14.1

      - name: Run tests
        run: zig test src/root.zig
